application: s~golden-cove-356
version: 5
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /fonts
  static_dir: fonts

- url: /_ah/channel/.*
  script: main.app

- url: /.*
  script: main.app
  login: required

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

inbound_services:
- channel_presence

builtins:
- remote_api: on